### ISSUE TITLE
No meaningful error messages

### ISSUE THREAD

**Issue by marc-sturm** [PavlidisLab/rgr#113]
Hi,

Marc from Tübingen, Germany here.

Yesterday, we had a user that entered an invalid URL in the website field of the profile (no "https://").
He tried several times, but in the end gave up to create a profile.

Unfortunately the error message "must be a valid URL" is only in the application log, but no meaningful error message is shown in the GUI:
![grafik](https://user-images.githubusercontent.com/5638144/134514689-91fb6e78-b97e-41c7-a2b0-8551d03b7c06.png)

Could you please improve the error message to include field and error message in case of an error.
If you touch the profile code, you could also fix the trucation of the fields (e.g. Organization in the screenshot).

Thanks,
  Marc

**Comment by arteymix** [comment]
I'm working on a quickfix for this by passing the validation result to the browser and generating a better error message. 

The ideal solution is described #19 and would be use simpler form and binding validation results directly to the fields like we do for the registration.

The truncation in the fields have already been fixed in 9111ee5f9076101ed0f4b1ac8b9e42524dceab06 and released in the 1.4.4.

**Comment by arteymix** [comment]
The fix actually binds error messages to fields, since it was simpler to do that than to generate a list of errors. I'll schedule it for the 1.4.6 release.

**Comment by arteymix** [comment]
I'll just mention here that I attempted to use the Bootstrap is-invalid and invalid-feedback classes, but it was not working as expected like it does for registration. I resorted to just simply use text-danger for the message
